name: Run Benchmark


permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      action_input:
        required: false
        type: string
      reuse_result:
        default: 'off'
        type: choice
        options: 
          - 'off'
          - per_branch
          - per_os

env:
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  RELEASE_TAG: "BenchmarkResult"

jobs:
  benchmark:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/checkout@v4

      - name: Install zip using Chocolatey
        if: matrix.os == 'windows-latest'
        run: choco install zip -y
        shell: powershell

      - name: Run benchmark script
        shell: bash
        env:
          CURRENT_OS: "${{ matrix.os }}"
          ACTION_INPUT: "${{ inputs.action_input }}"
          REUSE_RESULT: "${{ inputs.reuse_result }}"
        run: |
          mkdir -p ./target/upload
          chmod +x ./run.sh
          bash run.sh

      - name: Package results
        shell: bash
        id: pack_result
        run: |
          if [ -z "$(ls -A ./target/upload 2>> /dev/null)" ]; then
            echo "need_upload=false" >> $GITHUB_OUTPUT
            echo "Upload directory is empty."
          else
            echo "need_upload=true" >> $GITHUB_OUTPUT

            mkdir -p ./target/@artifacts/

            cd ./target/upload
            for item in *; do
              zip -r "../@artifacts/${item}.zip" "$item"
            done
            
            cd ../..
            ARTIFACTS=$(find ./target/@artifacts/ -type f -printf "%p\n")
            echo "FILES=$ARTIFACTS" >> $GITHUB_ENV
          fi

      - name: Upload artifacts
        if: steps.pack_result.outputs.need_upload == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: benchmark result on ${{ matrix.os }}
          path: ./target/@artifacts/*.zip
          retention-days: 1

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.FILES }}
          tag_name: ${{ env.RELEASE_TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
